# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

includes:
  docker: .tasks/dockertasks.yml
  _hugo: .tasks/hugotasks.yml
  _vale: .tasks/valetasks.yml

tasks:
  build:prod:
    desc: Build Production container
    cmds:
      - task: docker:build-prod

  start:prod:
    desc: Start the production containers
    cmds:
      - task: docker:start-prod

  stop:prod:
    desc: Stop the production containers
    cmds:
      - task: docker:stop-prod

  start:dev:
    desc: Start the development containers
    cmds:
      - task: docker:start-dev

  stop:dev:
    desc: Stop development containers
    cmds:
      - task: docker:stop-dev

  restart:dev:
    desc: Restart running development environment (or start it, if it's not running)
    cmds:
      - task: docker:restart-dev

  reset:dev:
    desc: Hard reset the development environment, bring it down before starting back up
    cmds:
      - task: docker:reset-dev

  hugo:build:
    desc: Build Hugo site locally
    cmds:
      - task: _hugo:build

  hugo:serve:
    desc: Serve Hugo site locally
    cmds:
      - task: _hugo:serve

  vale:sync:
    desc: Synchronize Vale styles
    cmds:
      - task: _vale:vale-sync

  vale:content:
    desc: Run vale on content/ dir
    cmds:
      - task: _vale:vale-lint-content
