# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

includes:
  builder: .tasks/build.yml

tasks:
  build:prod:
    desc: Build Production container
    cmds:
      - task: builder:prod
