# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  prod:
    desc: Build Production container
    dir: .containers/prod
    cmds:
      - cmd: docker compose build --no-cache
