resources:
  ## Blog repo
  - name: repo
    type: git
    source:
      uri: https://github.com/redjax/blog.git
      username: redjax
      # password: <set your password by running this: fly set-pipeline -p pipeline-name -v github-pat=ghp_...

jobs:
  - name: build-and-test
    plan:
      ## Clone repo
      - get: repo

      - task: build-hugo-site
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hugomods/hugo
              tag: debian-exts
          inputs:
            - name: repo
          outputs:
            - name: public-site
          caches:
            - path: /tmp/hugo_cache
          params:
            HUGO_CACHEDIR: /tmp/hugo_cache
          run:
            path: sh
            args:
              - -c
              - |
                cd repo
                hugo --gc --minify --destination ../public-site
